# Generated by Django 4.2 on 2024-03-19 23:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.crypto
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                (
                    "advertisement_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("platform_name", models.CharField(max_length=100)),
                ("platform_tax", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "property_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("max_guests", models.PositiveIntegerField()),
                ("bathrooms_quantity", models.PositiveIntegerField()),
                ("pets_allowed", models.BooleanField(default=False)),
                ("cleaning_fee", models.PositiveIntegerField()),
                ("activation_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "booking_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "booking_code",
                    models.CharField(
                        default=django.utils.crypto.get_random_string,
                        max_length=12,
                        unique=True,
                    ),
                ),
                ("check_in_date", models.DateField()),
                ("check_out_date", models.DateField()),
                ("total_price", models.PositiveIntegerField()),
                ("comment", models.TextField(blank=True, null=True)),
                ("guests_count", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "advertisement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="booking.advertisement",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="advertisement",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="booking.property"
            ),
        ),
    ]
