# Generated by Django 4.2 on 2024-03-11 00:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('max_guests', models.PositiveIntegerField()),
                ('bathrooms_quantity', models.PositiveIntegerField()),
                ('pets_allowed', models.BooleanField(default=False)),
                ('cleaning_fee', models.PositiveIntegerField()),
                ('activation_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
